.catalog:
  name: "Zabbix"
  version: 1.0
  description: "Zabbix Server, Zabbix Web, Zabbix Agent"
  uuid: zabbix.1-0
  questions:
    - variable: "MYSQL_USER"
      description: "Choose MySQL user name"
      label: "MySQL user"
      required: true
      type: "string"

    - variable: "MYSQL_PASSWORD"
      description: "Choose MySQL password"
      label: "MySQL password"
      required: true
      type: "password"

mariadb:
  scale: 1
zabbix-server:
  scale: 1
zabbix-web:
  scale: 1
zabbix-web-lb:
  scale: 1
  start_on_create: true
  lb_config:
    certs: []
    port_rules:
    - priority: 1
      protocol: http
      service: zabbix-web
      source_port: 9090
      target_port: 80
  health_check:
    response_timeout: 2000
    healthy_threshold: 2
    port: 42
    unhealthy_threshold: 3
    interval: 2000
